### ISSUE TITLE
Video Title Formatting issue

### ISSUE THREAD

**Issue by BDaddyG** [pastapojken/Myflix#11]
Hello!

I've discovered an issue with the home movie title format where one video title is overwriting another video title.

![Label-Issue-Myflix](https://user-images.githubusercontent.com/29808864/123285606-cea3e400-d4d2-11eb-9cf0-249c988fb8bd.png)

Looking closer, I see that I'm using an underscore as a word separator in the titles of the videos that are having issues.

Testing, I changed the underscores to dashes and the title is now wrapping correctly.
![Label-Issue-Myflix-fixed-with-dashes](https://user-images.githubusercontent.com/29808864/123289509-2728b080-d4d6-11eb-9243-6fa41f8f288d.png)

Guess this is turning more into an Video Titling FYI: if you want title wrapping don't use underscores to separate words.

Any idea as to the the reason the titles don't wrap if using an underscore?

Thanks!

**Comment by farfalleflickan** [comment]
Hi!

This was a bit interesting, apparently by default underscores are "unwrappable". I've updated the CSS in `movie.css` to fix this and now text should wrap no matter what.

**Comment by BDaddyG** [comment]
To play devil's advocate.. would it be best to leave the default action for underscore as "unwrappable" (it must have been set that way in the standards for a reason) and have a FAQ item that states underscore don't wrap?
