### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by mcat-ee** [pastapojken/Myflix#2]
This would be a great project for dockerization!

(Posting this issue to remind me to make a Dockerfile later, or for somebody to beat me to doing)

**Comment by farfalleflickan** [comment]
I haven't used Docker much, but I will look into it! ;) 
...you are also more than welcome to make a pull request with a dockerfile if you want! ;)

**Comment by farfalleflickan** [comment]
I'm honestly a bit confused by Docker, or rather by how this project would benefit from it... Is your idea to create a Dockerfile that integrates this with a webserver?

**Comment by mcat-ee** [comment]
This project would benefit from being dockerized as it would mean there's no installation or setup really required - you could say `docker run myflix -e database_host ... -e database_user ... and so forth` and the system would start working! No figuring out dependencies, no determining if there is some sort of OS problem that may affect functionality, just ensuring you have docker.

Also you could then make a docker-compose (or similar orchestration file) which could also bring up a database server at the same time!

Docker essentially means that (amongst other things) you don't have to worry about the underlying infrastructure or host operating system.

**Comment by farfalleflickan** [comment]
Yeah, I figured it would be something like that. I noticed (cus i'm a stalker) that @eyedeekay has forked the project and has been working on it ;)

**Comment by eyedeekay** [comment]
Yeah actually it's working pretty well, but I did it in Alpine so I want to make sure I don't run into anything wierd because of busybox ash. Since there's an interest, I'll try and get it together in the next couple days.
