### ISSUE TITLE
Filename as labels under thumbnails

### ISSUE THREAD

**Issue by KeithGraber** [pastapojken/Myflix#6]
Hello!

Would it be possible to have the video filename as a label under the thumbnail?  All my videos are non-commercial (think home videos, etc) so have no TMDB related information.

And is there of way of presenting the videos in reverse order, so the newest video is listed first?  For example, my filenames are formatted like: WhatsHappening-2018-12-20.mp4 and WhatsHappening-2019-03-28.mp4, and I want the 2019 video listed before the 2018 video.

Thanks for creating this project!

**Comment by farfalleflickan** [comment]
Hi!

Yes, this would totally be possible with a couple of tweaks to some scripts. From the program's point of view it's basically looking at the files as if they were single movies. I think the only tweaks needed would be to parse for a date in the filename and to add filenames to the div's in the HTML.
I will try to look into this tomorrow :) Unsure about an ETA but shouldn't be too much work.
Thanks for using this project :)

**Comment by farfalleflickan** [comment]
Lol, nevermind this didn't take much at all...
I've added the feature, you can enable it in the config by setting "homeMovies" to true. Doing this will run custom scripts that ignore subtitles, title, ID & poster metadata. Instead an automatic snapshot is taken from the file and used as "poster", the ID is set as the date (taken from the filename). 
Let me know if this works :)

**Comment by KeithGraber** [comment]
Works great!  Thanks for the short turn around time!

I have some other enhancement requests, do you want me to continue in this ticket or open new ones?

Thanks again, I've been looking for something lite and easy to use like this for a long time!

**Comment by farfalleflickan** [comment]
You are welcome! Please open new ones :) 
I can't promise I will be as fast as with this one but I will try ;)
