### ISSUE TITLE
Update System Requirements

### ISSUE THREAD

**Issue by KeithGraber** [pastapojken/Myflix#8]
Hi pastapojken!

In the list of requirements you didn't list "sponge".  Purely cosmetic i know, but thought people might want to install so they don't see error messages about sponge not being found when running the scripts.

On Ubuntu "sponge" can be installed with the moreutils package (apt install moreutils).

Thanks!

**Comment by farfalleflickan** [comment]
Hi!

Thanks for noticing that, it has been fixed :)
