### ISSUE TITLE
Remove file extenstion from the index page.

### ISSUE THREAD

**Issue by KeithGraber** [pastapojken/Myflix#9]
Hello!

Been using Myflix daily for the last year and still going strong!

Would it be possible to have the .mp4 extension removed from the movie names on the index page for Home Movies?

Thanks!

**Comment by farfalleflickan** [comment]
Hi!

I'm always happy to hear I'm not the only one :D
I've patched `bHMhtml.sh` accordingly, haven't tested it but should work.

Please report back so I can close the issue, thanks!

**Comment by KeithGraber** [comment]
the changes worked!  the extension is no longer shown on the index page.

Thanks for the change!
